version: '3'
services:
  find-keywords:
    build:
      context: .
      args:
        config_path: config/$ENV
        base_image: jupyter/pyspark-notebook:spark-3.1.2
    container_name: find-keywords-container
    user: root
    image: dna/$SERVICE
    working_dir: /opt/dna/$SERVICE
    env_file:
      - config/$ENV/.env
    #  - .env
    ports:
      - ${JUPYTER_PORT-8083}:${JUPYTER_PORT-8083}
      - ${SPARK_UI_PORT-4043}:${SPARK_UI_PORT-4043}
    volumes:
      - .:/opt/dna/$SERVICE
      - .:/src # Used by pre-commit on pytest step
      - ./config/$ENV:/home/jovyan/dna
      - ./datalake:/datalake
      - ./datalake/scikit_learn_data:/home/jovyan/scikit_learn_data
      - ./config/$ENV:/opt/myra/configs/cluster/
    entrypoint: ./config/$ENV/actions/run.sh
