version: 2
orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@2.1.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Publishing wheel to JFrog
          command: |
            set -e
            echo -e "[global]\index-url = https://$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD@inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi/simple" >> ~/*
            pip install -r requirements.txt
            pip install --upgrade twine
            bash -c "python3 setup.py bdist_wheel && twine upload --repository-url https://inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD dist/*"