version: 2
jobs:     
  build:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      # - run: mvn dependency:go-offline -X          
      #- run:
      #    name: maven build
      #    command: |
      #      mvn clean install
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            ./jfrog config add artifactory-server --artifactory-url https://inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi --user=$ARTIFACTORY_USERNAME --password=$ARTIFACTORY_PASSWORD --interactive=false
            ./jfrog rt u dna-ink-pypi/dna-ink-pypi --build-name=api-0.1.0-py3-none-any.whl --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce api-0.1.0-py3-none-any.whl $CIRCLE_BUILD_NUM  # collects all environment variables on the agent
            ./jfrog rt bp api-0.1.0-py3-none-any.whl $CIRCLE_BUILD_NUM  # attaches ^^ to the build in artifactory