version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: ~/repo
    steps:
      - checkout
      #- run: mvn dependency:go-offline -X
      #- run:
      #    name: maven build
      #    command: |
      #      mvn clean install
      - run:
          name: Install JFrog CLI
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Push to Artifactory
          command: |
            bash -c "python3 setup.py bdist_wheel && twine upload --repository-url https://inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi dist/*"