version: 2
orbs:
  python: circleci/python@0.2.1
  gcp-cli: circleci/gcp-cli@2.1.0
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - run:
          name: Publishing wheel to JFrog
          command: |
            set -e
            mkdir /home/circleci/.pip
            echo -e "[global]\index-url = https://cloud.junior@hotmail.com:6uTjkXKR6eWUsYm!@inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi/simple" >> /home/circleci/.pip/pip.conf
            pip config list -v
            pip install --upgrade pip
            pip install -r requirements.txt
            pip install --upgrade twine
            bash -c "python3 setup.py bdist_wheel && twine upload -u cloud.junior@hotmail.com -p 6uTjkXKR6eWUsYm! --repository-url https://inkdna.jfrog.io/artifactory/api/pypi/dna-ink-pypi dist/* --verbose"